### ISSUE TITLE
Additional Fonts

### ISSUE THREAD

**Issue by alterechtschreibung** [dschuermann/document-viewer#10]
Can you please add

Linux Libertine and Linux Biolinum
http://www.linuxlibertine.org/

and the DejaVu Fonts
http://dejavu-fonts.org/wiki/Main_Page

**Comment by tuxor1337** [comment]
So, maybe my question is not really issue specific: May I ask why you want to change the font at all? Don't pdfs usually ship their own fonts? Can you point me to other pdf viewers that have the option of changing the font?

I'm asking because with an update of mupdf, it seems a bit hard to keep the old font settings. And at the moment, I feel like you could simply remove this feature altogether without doing a lot of harm.

**Comment by tuxor1337** [comment]
Okay, latest merge removed the ability to load external fonts. It's still in the settings menu, but it doesn't work.

**Comment by KrasnayaPloshchad** [comment]
Dominik bave another project to provide additional fonts for Document Viewer

https://github.com/dschuermann/document-viewer-fontpack

F-droid can download this app

**Comment by KrasnayaPloshchad** [comment]
The currrnt version can create folder to load fonts from external sdcard, such as "/sdcard/.org.sufficientlysecure.viewer/fonts".

**Comment by tuxor1337** [comment]
I know that document viewer has this font settings and stuff and I know that e.g. Sumatra PDF is providing a similar functionality. But this functionality seems to break the fonts in some situation (cf. #51). It seems to me, like the overall experience is much smoother when you abstain from messing around with the font settings.

What is the benefit from this ability to customize the default font setting? Can you point me to a pdf document or a certain situation where this plays a roll?

**Comment by tuxor1337** [comment]
Okay, I managed to implement the font setting as it should be. It shouldn't be particularly hard to add more fonts to the fontpackage now.

**Comment by tuxor1337** [comment]
Fonts added to document-viewer-fontpack :)
