### ISSUE TITLE
Missing fonts?

### ISSUE THREAD

**Issue by mase76** [dschuermann/document-viewer#51]
The german pdf manuals from gnupg.org are unreadable. Seems that there are missing fonts.

**Comment by tuxor1337** [comment]
I have no idea, what's the reason for this issue, but it should be able to fix this by updating the mupdf-version used in this android app. 

Some background: This app includes mupdf-C-libraries via Android NDK and so does the Android app MuPDF. But with the latest version of MuPDF, I don't have any font problems. Unfortunately, I'm not familiar with Android NDK. Otherwise it would be possible to fix this issue by simply using the same NDK stuff that is used in the MuPDF Android app (http://git.ghostscript.com/?p=mupdf.git;a=tree;f=platform/android/jni).

**Comment by tuxor1337** [comment]
As I suspected, this problem indeed vanishes (so does #62) once mupdf is updated to the latest version. See my fork for more details: https://github.com/tuxor1337/document-viewer

Note that we can't merge the fork to master at the moment, because the fork lacks nightmode and slow cmyk to rgb.

**Comment by KrasnayaPloshchad** [comment]
Android Developer website may have some available guides for Android NDK

**Comment by tuxor1337** [comment]
Okay, I think we're ready for merging. This issue should be fixed now.
